/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gato;

public class GatoInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form GatoInterfaz
     */
    public GatoInterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gato = Gato.getGato("Jugador 1", "Jugador 2");

        mensaje = new javax.swing.JLabel();

        ceroCero = new javax.swing.JButton();
        ceroUno = new javax.swing.JButton();
        ceroDos = new javax.swing.JButton();

        unoCero = new javax.swing.JButton();
        unoUno = new javax.swing.JButton();
        unoDos = new javax.swing.JButton();

        dosCero = new javax.swing.JButton();
        dosUno = new javax.swing.JButton();
        dosDos = new javax.swing.JButton();

        ceroCero.setText("0 0");
        ceroUno.setText("0 1");
        ceroDos.setText("0 2");

        unoCero.setText("1 0");
        unoUno.setText("1 1");
        unoDos.setText("1 2");

        dosCero.setText("2 0");
        dosUno.setText("2 1");
        dosDos.setText("2 2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        //Fila superior
        ceroCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroCeroActionPerformed(evt);
            }
        });

        ceroUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroUnoActionPerformed(evt);
            }
        });

        ceroDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroDosActionPerformed(evt);
            }
        });

        //Fila media
        unoCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoCeroActionPerformed(evt);
            }
        });

        unoUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoUnoActionPerformed(evt);
            }
        });

        unoDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoDosActionPerformed(evt);
            }
        });

        //Fila inferior
        dosCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosCeroActionPerformed(evt);
            }
        });

        dosUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosUnoActionPerformed(evt);
            }
        });

        dosDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosDosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ceroCero, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ceroUno, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ceroDos, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addContainerGap()
//                                                .addComponent(ceroCero, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                .addComponent(ceroUno, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                .addComponent(ceroDos, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addGap(18, 18, 18)
//                                                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addContainerGap()
//                                                .addComponent(unoCero, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addContainerGap()
//                                                .addComponent(unoUno, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addContainerGap()
//                                                .addComponent(unoDos, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addGap(18, 18, 18))
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addContainerGap()
//                                                .addComponent(dosCero, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addContainerGap()
//                                                .addComponent(dosUno, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addContainerGap()
//                                                .addComponent(dosDos, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                )
                                .addContainerGap(80, Short.MAX_VALUE)
                        )
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(ceroCero, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ceroUno, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ceroDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(unoCero, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(unoUno, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(unoDos, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(dosCero, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(dosUno, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(dosDos, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        )
                                        .addComponent(unoCero, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ceroCero, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ceroCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoUnoActionPerformed
        // TODO add your handling code here:i
        String resultado = gato.tirar(0, 0);
        if (resultado.equals("Espacio ocupado")) {
            mensaje.setText(resultado);
        } else {
            ceroCero.setText(resultado);
        }
    }

    private void ceroUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoDosActionPerformed
        // TODO add your handling code here:
        String resultado = gato.tirar(0, 1);
        if (resultado.equals("Espacio ocupado")) {
            mensaje.setText(resultado);
        } else {
            ceroUno.setText(resultado);
        }
    }//GEN-LAST:event_unoDosActionPerformed

    private void ceroDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoTresActionPerformed
        // TODO add your handling code here:
        String resultado = gato.tirar(0, 2);
        if (resultado.equals("Espacio ocupado")) {
            mensaje.setText(resultado);
        } else {
            ceroDos.setText(resultado);
        }

    }//GEN-LAST:event_unoTresActionPerformed

    private void unoCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoUnoActionPerformed
        // TODO add your handling code here:i
        String resultado = gato.tirar(0, 0);
        if (resultado.equals("Espacio ocupado")) {
            mensaje.setText(resultado);
        } else {
            ceroCero.setText(resultado);
        }
    }

    private void unoUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoDosActionPerformed
        // TODO add your handling code here:
        String resultado = gato.tirar(0, 1);
        if (resultado.equals("Espacio ocupado")) {
            mensaje.setText(resultado);
        } else {
            ceroUno.setText(resultado);
        }
    }//GEN-LAST:event_unoDosActionPerformed

    private void unoDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoTresActionPerformed
        // TODO add your handling code here:
        String resultado = gato.tirar(0, 2);
        if (resultado.equals("Espacio ocupado")) {
            mensaje.setText(resultado);
        } else {
            ceroDos.setText(resultado);
        }

    }//GEN-LAST:event_unoTresActionPerformed

    private void dosCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoUnoActionPerformed
        // TODO add your handling code here:i
        String resultado = gato.tirar(0, 0);
        if (resultado.equals("Espacio ocupado")) {
            mensaje.setText(resultado);
        } else {
            ceroCero.setText(resultado);
        }
    }

    private void dosUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoDosActionPerformed
        // TODO add your handling code here:
        String resultado = gato.tirar(0, 1);
        if (resultado.equals("Espacio ocupado")) {
            mensaje.setText(resultado);
        } else {
            ceroUno.setText(resultado);
        }
    }//GEN-LAST:event_unoDosActionPerformed

    private void dosDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoTresActionPerformed
        // TODO add your handling code here:
        String resultado = gato.tirar(0, 2);
        if (resultado.equals("Espacio ocupado")) {
            mensaje.setText(resultado);
        } else {
            ceroDos.setText(resultado);
        }

    }//GEN-LAST:event_unoTresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GatoInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GatoInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GatoInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GatoInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GatoInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Gato gato;
    private javax.swing.JLabel mensaje;

    //Fila Superior
    private javax.swing.JButton ceroUno;
    private javax.swing.JButton ceroDos;
    private javax.swing.JButton ceroCero;

    //Fila Media
    private javax.swing.JButton unoCero;
    private javax.swing.JButton unoUno;
    private javax.swing.JButton unoDos;

    //Fila Inferior
    private javax.swing.JButton dosCero;
    private javax.swing.JButton dosUno;
    private javax.swing.JButton dosDos;

    // End of variables declaration//GEN-END:variables
}
